apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: dev
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg==    # base64 of 'mongoadmin'
  mongo-root-password: c2VjcmV0           # base64 of 'secret'
